const state = () => ({
	apartments: [
		{
			id: 1,
			image: "/img/general/catalog/secondary_apartment-1.webp",
			rooms: 1,
			district: "Дзержинский",
			address: "ул. им. Хорошева, 16",
			area: 44.7,
			price: 4.7,
			link: "/",
		},
		{
			id: 2,
			image: "/img/general/catalog/secondary_apartment-2.webp",
			rooms: 2,
			district: "Дзержинский",
			address: "ул. им. Константина Симонова, 2",
			area: 47.9,
			price: 6.25,
			link: "/",
		},
		{
			id: 3,
			image: "/img/general/catalog/secondary_apartment-3.webp",
			rooms: 1,
			district: "Советский",
			address: "ул. Тимирязева, 46А",
			area: 39.3,
			price: 3.55,
			link: "/",
		},
		{
			id: 4,
			image: "/img/general/catalog/secondary_apartment-4.webp",
			rooms: 3,
			district: "Центральный",
			address: "ул. Советская, 20",
			area: 85,
			price: 8.2,
			link: "/",
		},
		{
			id: 5,
			image: "/img/general/catalog/secondary_apartment-5.webp",
			rooms: 2,
			district: "Дзержинский",
			address: "ул. 8-й Воздушной Армии, 39",
			area: 50.3,
			price: 4.2,
			link: "/",
		},
		{
			id: 6,
			image: "/img/general/catalog/secondary_apartment-6.webp",
			rooms: 2,
			district: "Советский",
			address: "ул. Тимирязева, 15",
			area: 55.2,
			price: 6,
			link: "/",
		},
		{
			id: 7,
			image: "/img/general/catalog/secondary_apartment-7.webp",
			rooms: 2,
			district: "Центральный",
			address: "пр-т им. В.И. Ленина, 16",
			area: 56,
			price: 8.6,
			link: "/",
		},
		{
			id: 8,
			image: "/img/general/catalog/secondary_apartment-8.webp",
			rooms: 1,
			district: "Центральный",
			address: "ул. Селенгинская, 11",
			area: 50,
			price: 7,
			link: "/",
		},
		{
			id: 9,
			image: "/img/general/catalog/secondary_apartment-9.webp",
			rooms: 1,
			district: "Центральный",
			address: "ул. Советская, 19",
			area: 33,
			price: 3,
			link: "/",
		},
		{
			id: 10,
			image: "/img/general/catalog/secondary_apartment-10.webp",
			rooms: 2,
			district: "Кировский",
			address: "ул. Санаторная, 6",
			area: 55.6,
			price: 5.7,
			link: "/",
		},
		{
			id: 11,
			image: "/img/general/catalog/secondary_apartment-11.webp",
			rooms: 1,
			district: "Ворошиловский",
			address: "ул. Рабоче-Крестьянская, 57",
			area: 31.3,
			price: 2.8,
			link: "/",
		},
		{
			id: 12,
			image: "/img/general/catalog/secondary_apartment-12.webp",
			rooms: 3,
			district: "Ворошиловский",
			address: "ул. Елисеева, 1",
			area: 85,
			price: 7.9,
			link: "/",
		},
		{
			id: 13,
			image: "/img/general/catalog/secondary_apartment-13.webp",
			rooms: 2,
			district: "Дзержинский",
			address: "ул. Констанина Симонова, 28",
			area: 52,
			price: 4.1,
			link: "/",
		},
		{
			id: 14,
			image: "/img/general/catalog/secondary_apartment-14.webp",
			rooms: 1,
			district: "Центральный",
			address: "ул. Пражская, 16А",
			area: 32.1,
			price: 3.8,
			link: "/",
		},
		{
			id: 15,
			image: "/img/general/catalog/secondary_apartment-15.webp",
			rooms: 3,
			district: "Дзержинский",
			address: "ул. Краснополянская, 2",
			area: 54.9,
			price: 4,
			link: "/",
		},
		{
			id: 16,
			image: "/img/general/catalog/secondary_apartment-16.webp",
			rooms: 2,
			district: "Советский",
			address: "ул. Академика Комарова, 79",
			area: 53.5,
			price: 3.8,
			link: "/",
		},
		//* dublicate
		{
			id: 17,
			image: "/img/general/catalog/secondary_apartment-1.webp",
			rooms: 1,
			district: "Дзержинский",
			address: "ул. им. Хорошева, 16",
			area: 44.7,
			price: 4.7,
			link: "/",
		},
		{
			id: 18,
			image: "/img/general/catalog/secondary_apartment-2.webp",
			rooms: 2,
			district: "Дзержинский",
			address: "ул. им. Константина Симонова, 2",
			area: 47.9,
			price: 6.25,
			link: "/",
		},
		{
			id: 19,
			image: "/img/general/catalog/secondary_apartment-3.webp",
			rooms: 1,
			district: "Советский",
			address: "ул. Тимирязева, 46А",
			area: 39.3,
			price: 3.55,
			link: "/",
		},
		{
			id: 20,
			image: "/img/general/catalog/secondary_apartment-4.webp",
			rooms: 3,
			district: "Центральный",
			address: "ул. Советская, 20",
			area: 85,
			price: 8.2,
			link: "/",
		},
		{
			id: 21,
			image: "/img/general/catalog/secondary_apartment-5.webp",
			rooms: 2,
			district: "Дзержинский",
			address: "ул. 8-й Воздушной Армии, 39",
			area: 50.3,
			price: 4.2,
			link: "/",
		},
		{
			id: 22,
			image: "/img/general/catalog/secondary_apartment-6.webp",
			rooms: 2,
			district: "Советский",
			address: "ул. Тимирязева, 15",
			area: 55.2,
			price: 6,
			link: "/",
		},
		{
			id: 23,
			image: "/img/general/catalog/secondary_apartment-7.webp",
			rooms: 2,
			district: "Центральный",
			address: "пр-т им. В.И. Ленина, 16",
			area: 56,
			price: 8.6,
			link: "/",
		},
		{
			id: 24,
			image: "/img/general/catalog/secondary_apartment-8.webp",
			rooms: 1,
			district: "Центральный",
			address: "ул. Селенгинская, 11",
			area: 50,
			price: 7,
			link: "/",
		},
		{
			id: 25,
			image: "/img/general/catalog/secondary_apartment-9.webp",
			rooms: 1,
			district: "Центральный",
			address: "ул. Советская, 19",
			area: 33,
			price: 3,
			link: "/",
		},
		{
			id: 26,
			image: "/img/general/catalog/secondary_apartment-10.webp",
			rooms: 2,
			district: "Кировский",
			address: "ул. Санаторная, 6",
			area: 55.6,
			price: 5.7,
			link: "/",
		},
		{
			id: 27,
			image: "/img/general/catalog/secondary_apartment-11.webp",
			rooms: 1,
			district: "Ворошиловский",
			address: "ул. Рабоче-Крестьянская, 57",
			area: 31.3,
			price: 2.8,
			link: "/",
		},
		{
			id: 28,
			image: "/img/general/catalog/secondary_apartment-12.webp",
			rooms: 3,
			district: "Ворошиловский",
			address: "ул. Елисеева, 1",
			area: 85,
			price: 7.9,
			link: "/",
		},
		{
			id: 29,
			image: "/img/general/catalog/secondary_apartment-13.webp",
			rooms: 2,
			district: "Дзержинский",
			address: "ул. Констанина Симонова, 28",
			area: 52,
			price: 4.1,
			link: "/",
		},
		{
			id: 30,
			image: "/img/general/catalog/secondary_apartment-14.webp",
			rooms: 1,
			district: "Центральный",
			address: "ул. Пражская, 16А",
			area: 32.1,
			price: 3.8,
			link: "/",
		},
		{
			id: 31,
			image: "/img/general/catalog/secondary_apartment-15.webp",
			rooms: 3,
			district: "Дзержинский",
			address: "ул. Краснополянская, 2",
			area: 54.9,
			price: 4,
			link: "/",
		},
		{
			id: 32,
			image: "/img/general/catalog/secondary_apartment-16.webp",
			rooms: 2,
			district: "Советский",
			address: "ул. Академика Комарова, 79",
			area: 53.5,
			price: 3.8,
			link: "/",
		},
	],
})

const getters = {}

const mutations = {

}

const actions = {}

export default {
	state,
	getters,
	mutations,
	actions
}